name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull authentication docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authentication:latest

      - name: Deploy services with Docker Compose
        run: |
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          docker-compose up -d --remove-orphans
