name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authentication:latest
      - name: Delete old docker container
        run: sudo docker rm -f authentication-container || true
      - name: Run docker container
        run: sudo docker run -d -p 3001:3001 --name authentication-container ${{ secrets.DOCKER_USERNAME }}/authentication
