name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull authentication docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authentication:latest

      - name: Remove old authentication container
        run: sudo docker rm -f authentication-container || true

      - name: Remove old MySQL container
        run: sudo docker rm -f mysql-container || true

      - name: Remove old images
        run: sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/authentication:latest || true

      - name: Deploy services with Docker Compose
        run: |
          echo "Setting environment variables..."
          export DB_ROOT_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"
          export DB_NAME="${{ secrets.DB_NAME }}"
          export DB_USER="${{ secrets.DB_USER }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

          echo "Starting Docker Compose..."
          docker-compose up -d --remove-orphans
