name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull authentication docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authentication:latest

      - name: Stop and remove old authentication container
        run: sudo docker rm -f authentication-container || true

      - name: Start MySQL container
        run: |
          MYSQL_CONTAINER=$(sudo docker ps -q -f name=mysql-container)
          if [ -n "$MYSQL_CONTAINER" ]; then
              echo "MySQL container is already running"
          else
              sudo docker run -d --name mysql-container \
                -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} \
                -e MYSQL_DATABASE=${{ secrets.DB_NAME }} \
                -e MYSQL_USER=${{ secrets.DB_USER }} \
                -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
                -p 3306:3306 \
                mysql:8
          fi

      - name: Run docker container
        run: sudo docker run -d -p 3001:3001 --name authentication-container \
          -- link mysql-container:mysql \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_USER=${{ secrets.DB_USER }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          ${{ secrets.DOCKER_USERNAME }}/authentication
