name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file for Docker Compose
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_CLIENT=${{ secrets.APP_CLIENT }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env

      - name: Verify .env file
        run: cat .env

      - name: Pull authentication docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/authentication:latest

      - name: Remove old authentication container
        run: docker rm -f authentication-container || true

      - name: Remove old MySQL container
        run: docker rm -f mysql-container || true

      - name: Remove old images
        run: |
          echo "Removing old images..."
          docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi

      - name: Deploy services with Docker Compose
        run: |
          echo "Starting Docker Compose..."
          docker-compose --env-file .env config
          docker-compose --env-file .env up -d --remove-orphans

      - name: Clean up .env file
        run: rm .env
